name: CI Workflow for C program  # The name of your workflow

# Run the action on specific events
on:
  push:         # Runs when a push is made to any branch
  pull_request: # Runs when a pull request is created

# Define the jobs (steps) that GitHub will run
jobs:
  build:
    runs-on: ubuntu-latest  # The machine where the action runs (Ubuntu by default)

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up the build environment (this example uses GCC for C programming)
    - name: Set up GCC
      run: sudo apt-get install gcc make

    # Step 3: Build the code
    - name: Build the code
      run: make

    # Step 4: Run the program
    - name: Run the program
      run: ./test
    
    # Step 5: Upload the build artifacts
    - name: Upload build artifact  # Corrected spelling of "build"
      uses: actions/upload-artifact@v3  # Corrected from "action" to "actions"
      with:
        name: compiled-binary  # Name of the artifact
        path: ./test  # Path to the compiled binary

